enableGlobalCache: false

enableTelemetry: false

logFilters:
  - level: discard
    text: "prettier is listed by your project with version 3.2.5, which doesn't satisfy what @xstate/cli (p68591) and other dependencies request (^2.0.0)."

nodeLinker: pnp

packageExtensions:
  "@algolia/autocomplete-core@*":
    peerDependencies:
      "@algolia/client-search": "*"
      algoliasearch: "*"
      search-insights: "*"
  "@algolia/autocomplete-plugin-algolia-insights@*":
    peerDependencies:
      "@algolia/client-search": "*"
      algoliasearch: "*"
  "@docsearch/react@*":
    peerDependencies:
      "@algolia/client-search": "*"
  "@docusaurus/core@*":
    peerDependencies:
      typescript: "*"
  "@docusaurus/theme-classic@*":
    peerDependencies:
      typescript: "*"
  "@docusaurus/theme-common@*":
    peerDependencies:
      typescript: "*"
  "@docusaurus/theme-search-algolia@*":
    peerDependencies:
      "@algolia/client-search": "*"
      search-insights: "*"
      typescript: "*"
  "@docusaurus/plugin-client-redirects@*":
    peerDependencies:
      typescript: "*"
  "@docusaurus/plugin-content-blog@*":
    peerDependencies:
      typescript: "*"
  "@docusaurus/plugin-content-docs@*":
    peerDependencies:
      typescript: "*"
  "@docusaurus/plugin-content-pages@*":
    peerDependencies:
      typescript: "*"
  "@docusaurus/plugin-sitemap@*":
    peerDependencies:
      typescript: "*"
  "@mui/x-data-grid@*":
    peerDependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
      "@types/react": "*"
  "@typescript-eslint/utils@*":
    peerDependencies:
      typescript: "*"
  "@xstate/cli@*":
    peerDependencies:
      prettier: "*"
  "@xstate/tools-shared@*":
    peerDependencies:
      "@babel/core": "*"
  eslint-config-airbnb-typescript@*:
    peerDependencies:
      eslint-plugin-import: "*"
  notistack@*:
    peerDependencies:
      csstype: "*"

yarnPath: .yarn/releases/yarn-4.3.1.cjs
