enableGlobalCache: false

enableTelemetry: false

logFilters:
  - level: discard
    text: "prettier is listed by your project with version 3.2.5, which doesn't satisfy what @xstate/cli (p68591) and other dependencies request (^2.0.0)."

nodeLinker: pnp

packageExtensions:
  "@mui/x-data-grid@*":
    # `@mui/x-data-grid` has `@mui/system` as a direct dependency.
    # We must state `@emotion/react` as a peer dependency here,
    # because otherwise the optional peer dependency in`@mu/system`
    # will not be satisfied.
    # See https://github.com/mui/mui-x/issues/12566
    peerDependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
      "@types/react": "*"
  "@xstate/cli@*":
    peerDependencies:
      prettier: "*"
  "@xstate/tools-shared@*":
    peerDependencies:
      "@babel/core": "*"
  notistack@*:
    peerDependencies:
      csstype: "*"

yarnPath: .yarn/releases/yarn-4.3.0.cjs
